name: settings_panel_android
description: Launch Android's Settings.Panel right from your Flutter app. Android-only plugin.
version: 0.1.2
author: Vince Varga <vince.varga@serial.dev>
homepage: https://github.com/dartsidedev/plugins/tree/master/packages/settings_panel_android
repository: https://github.com/dartsidedev/plugins
issue_tracker: https://github.com/dartsidedev/plugins/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: dev.dartside.plugins.settings_panel_android
    pluginClass: SettingsPanelAndroidPlugin
